# ~/.xinitrc

# Start the gnome-keyring-daemon
# @url https://wiki.archlinux.org/index.php/GNOME/Keyring#xinitrc_method
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)

# start i3 with loging
# exec i3 -V >> ~/i3log-$(date +'%F-%k-%M-%S') 2>&1
# start without loging
exec i3
